remote_theme: pages-themes/architect@v0.2.0
title: [Eid al-Adha]
description: [This site offers an explanation on the history behind Eid al-Adha, what muslims do to prepare for it, how they celebrate it, and some of my favorite memories of this day. ]
